# Опциональный Ingress для более удобного доступа
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: donation-app-ingress
  namespace: donation-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: donation-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: donation-nginx
            port:
              number: 80